### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by YJonmo** [dthanuja/ENG#1]
Hi there,

I have stereo endoscopic videos recorded using our custom built camera. 
I want to use this repository to get the depth and the pose. But I cannot find the code for the training using the new data. All I can see is about demo.

Or please let me know if I am missing training code somehow. 

Regards,
Jacob

**Comment by aspek2** [comment]
Hi Jacob, 

We have currently only released the test code and model. I realise it's not ideal but if you have a simple training framework in Tensorflow it could be used. Our training framework was a little adhoc, Sorry. But I believe all the key elements for making your own training script are there. 

Regards,
Andrew
