### ISSUE TITLE
Question: Why need to normalize optical flow using focal_length_x and focal_length_y

### ISSUE THREAD

**Issue by ruizengalways** [dthanuja/ENG#2]
https://github.com/dthanuja/ENG/blob/6d22690fc0a671109ec8dd16fbdbd3c7337aa425/vo_utils.py#L49

Hi Thanuja,

I went through your fantastic code. I am somehow confused in this line. Could you please explain to me why flow need to normalized using focal length? Thank you

**Comment by aspek2** [comment]
This falls out of the maths, when you calculate the Jacobian, you can you normalised camera coords or you have to incorporate the focal-length later. We chose to do it this way. This is in section 3.4 of the paper and section V.I in the supplementary material.
